definitions:
  user.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  user.LoginRes:
    properties:
      accestoken:
        type: string
      id:
        type: string
      refreshtoken:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  user.Password:
    properties:
      code:
        type: string
      email:
        type: string
      new_password:
        type: string
    type: object
  user.RegisterReq:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
      phone:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  user.RegisterRes:
    properties:
      id:
        type: string
    type: object
host: localhost:8085
info:
  contact: {}
  description: API Gateway of Authorazation
  title: User
  version: "1.0"
paths:
  /auth/change/password:
    post:
      description: it change your password
      parameters:
      - description: username and password
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/user.Password'
      responses:
        "200":
          description: message
          schema:
            type: string
        "400":
          description: Invalid date
          schema:
            type: string
        "500":
          description: error while reading from server
          schema:
            type: string
      summary: change password
      tags:
      - auth
  /auth/login:
    post:
      description: it generates new access and refresh tokens
      parameters:
      - description: username and password
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/user.LoginReq'
      responses:
        "200":
          description: tokens
          schema:
            type: string
        "400":
          description: Invalid date
          schema:
            type: string
        "500":
          description: error while reading from server
          schema:
            type: string
      summary: login user
      tags:
      - auth
  /auth/refresh:
    post:
      description: it changes your access token
      parameters:
      - description: all
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/user.LoginRes'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Invalid date
          schema:
            type: string
        "401":
          description: Invalid token
          schema:
            type: string
        "500":
          description: error while reading from server
          schema:
            type: string
      summary: Refresh token
      tags:
      - auth
  /auth/register:
    post:
      description: create new users
      parameters:
      - description: User info
        in: body
        name: info
        required: true
        schema:
          $ref: '#/definitions/user.RegisterReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.RegisterRes'
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Register user
      tags:
      - auth
swagger: "2.0"
